import { HatiSdk, StorageType } from "../index";

console.log("@hatish/hati-sdk-node");

(async () => {
  const hati = new HatiSdk({
    host: "localhost",
    port: 4242,
    // host: "roundhouse.proxy.rlwy.net",
    // port: 11402,
    // host: "monorail.proxy.rlwy.net",
    // port: 17092,
  });

  const valueMsg = JSON.stringify({
    ok: true,
    dziala: "tak to dziala\nsuper sprawa",
  });

  // for (let i = 0; i < 10000; i++) {
  const res = await hati.set("test_key", valueMsg, StorageType.MEMORY);
  console.log("res >>>> ", res);

  // const resGet = await hati.publish(`GET memory test_key1`);
  // console.log("resGet >>>> ", resGet);

  // const resHas = await hati.publish(`HAS memory test_key1`);
  // console.log("resHas >>>> ", resHas);

  // const resDelete = await hati.publish(`DELETE memory test_key1`);
  // console.log("resDelete >>>> ", resDelete);

  // const resHas2 = await hati.publish(`HAS memory test_key1`);
  // console.log("resHas2 >>>> ", resHas2);
  // }
  // await hati.publish(`SET key ${valueMsg}`);
  // await Promise.all([
  // hati.publish(`SET memory test_key1 ${valueMsg}`),
  // hati.publish(`GET memory test_key1`),
  // hati.publish(`SET memory test_key2 ${valueMsg}`),
  // hati.publish(`GET memory test_key2`),
  // hati.publish(`SET memory test_key3 ${valueMsg}`),
  // hati.publish(`GET memory test_key3`),
  // hati.publish(`SET memory test_key4 ${valueMsg}`),
  // hati.publish(`GET memory test_key4`),
  // hati.publish(`SET memory test_key5 ${valueMsg}`),
  // hati.publish(`GET memory test_key5`),
  // hati.publish(`SET memory test_key6 ${valueMsg}`),
  // hati.publish(`GET memory test_key6`),
  // hati.publish(`SET memory test_key7 ${valueMsg}`),
  // hati.publish(`GET memory test_key7`),
  // hati.publish(`SET memory test_key8 ${valueMsg}`),
  // hati.publish(`GET memory test_key8`),
  // hati.publish(`SET memory test_key9 ${valueMsg}`),
  // hati.publish(`GET memory test_key9`),
  // hati.publish(`SET memory test_key10 ${valueMsg}`),
  // hati.publish(`GET memory test_key10`),
  // hati.publish(`SET memory test_key1 ${valueMsg}`),
  // hati.publish(`GET memory test_key1`),
  // hati.publish(`SET memory test_key2 ${valueMsg}`),
  // hati.publish(`GET memory test_key2`),
  // hati.publish(`SET memory test_key3 ${valueMsg}`),
  // hati.publish(`GET memory test_key3`),
  // hati.publish(`SET memory test_key4 ${valueMsg}`),
  // hati.publish(`GET memory test_key4`),
  // hati.publish(`SET memory test_key5 ${valueMsg}`),
  // hati.publish(`GET memory test_key5`),
  // hati.publish(`SET memory test_key6 ${valueMsg}`),
  // hati.publish(`GET memory test_key6`),
  // hati.publish(`SET memory test_key7 ${valueMsg}`),
  // hati.publish(`GET memory test_key7`),
  // hati.publish(`SET memory test_key8 ${valueMsg}`),
  // hati.publish(`GET memory test_key8`),
  // hati.publish(`SET memory test_key9 ${valueMsg}`),
  // hati.publish(`GET memory test_key9`),
  // hati.publish(`SET memory test_key10 ${valueMsg}`),
  // hati.publish(`GET memory test_key10`),
  // hati.publish(`SET memory test_key1 ${valueMsg}`),
  // hati.publish(`GET memory test_key1`),
  // hati.publish(`SET memory test_key2 ${valueMsg}`),
  // hati.publish(`GET memory test_key2`),
  // hati.publish(`SET memory test_key3 ${valueMsg}`),
  // hati.publish(`GET memory test_key3`),
  // hati.publish(`SET memory test_key4 ${valueMsg}`),
  // hati.publish(`GET memory test_key4`),
  // hati.publish(`SET memory test_key5 ${valueMsg}`),
  // hati.publish(`GET memory test_key5`),
  // hati.publish(`SET memory test_key6 ${valueMsg}`),
  // hati.publish(`GET memory test_key6`),
  // hati.publish(`SET memory test_key7 ${valueMsg}`),
  // hati.publish(`GET memory test_key7`),
  // hati.publish(`SET memory test_key8 ${valueMsg}`),
  // hati.publish(`GET memory test_key8`),
  // hati.publish(`SET memory test_key9 ${valueMsg}`),
  // hati.publish(`GET memory test_key9`),
  // hati.publish(`SET memory test_key10 ${valueMsg}`),
  // hati.publish(`GET memory test_key10`),
  // hati.publish(`SET key ${valueMsg}`),
  // hati.publish(`SET key ${valueMsg}`),
  // hati.publish(`SET key ${valueMsg}`),
  // hati.publish(`SET key ${valueMsg}`),
  // hati.publish(`SET key ${valueMsg}`),
  // hati.publish(`SET key ${valueMsg}`),
  // hati.publish(`SET key ${valueMsg}`),
  // hati.publish(`SET key ${valueMsg}`),
  // hati.publish(`SET key ${valueMsg}`),
  // hati.publish(`SET key ${valueMsg}`),
  // hati.publish(`SET key ${valueMsg}`),
  // hati.publish(`SET key ${valueMsg}`),
  // hati.publish(`SET key ${valueMsg}`),
  // hati.publish(`SET key ${valueMsg}`),
  // hati.publish(`SET key ${valueMsg}`),
  // hati.publish(`SET key ${valueMsg}`),
  // hati.publish(`SET key ${valueMsg}`),
  // hati.publish(`SET key ${valueMsg}`),
  // hati.publish(`SET key ${valueMsg}`),
  // hati.publish(`SET key ${valueMsg}`),
  // hati.publish(`SET key ${valueMsg}`),
  // hati.publish(`SET key ${valueMsg}`),
  // hati.publish(`SET key ${valueMsg}`),
  // hati.publish(`SET key ${valueMsg}`),
  // hati.publish(`SET key ${valueMsg}`),
  // hati.publish(`SET key ${valueMsg}`),
  // hati.publish(`SET key ${valueMsg}`),
  // hati.publish(`SET key ${valueMsg}`),
  // hati.publish(`SET key ${valueMsg}`),
  // hati.publish(`SET key ${valueMsg}`),
  // hati.publish(`SET key ${valueMsg}`),
  // hati.publish(`SET key ${valueMsg}`),
  // hati.publish(`SET key ${valueMsg}`),
  // hati.publish(`SET key ${valueMsg}`),
  // hati.publish(`SET key ${valueMsg}`),
  // hati.publish(`SET key ${valueMsg}`),
  // hati.publish(`SET key ${valueMsg}`),
  // hati.publish(`SET key ${valueMsg}`),
  // hati.publish(`SET key ${valueMsg}`),
  // hati.publish(`SET key ${valueMsg}`),
  // hati.publish(`SET key ${valueMsg}`),
  // hati.publish(`SET key ${valueMsg}`),
  // hati.publish(`SET key ${valueMsg}`),
  // hati.publish(`SET key ${valueMsg}`),
  // hati.publish(`SET key ${valueMsg}`),
  // hati.publish(`SET key ${valueMsg}`),
  // hati.publish(`SET key ${valueMsg}`),
  // hati.publish(`SET key ${valueMsg}`),
  // hati.publish(`SET key ${valueMsg}`),
  // hati.publish(`SET key ${valueMsg}`),
  // hati.publish(`SET key ${valueMsg}`),
  // hati.publish(`SET key ${valueMsg}`),
  // hati.publish(`SET key ${valueMsg}`),
  // hati.publish(`SET key ${valueMsg}`),
  // hati.publish(`SET key ${valueMsg}`),
  // hati.publish(`SET key ${valueMsg}`),
  // hati.publish(`SET key ${valueMsg}`),
  // hati.publish(`SET key ${valueMsg}`),
  // /// ^^ 60clients * 50000r = 3,000,000r / 101s = 29.7K r/s <-- local
  // /// ^^ 60clients * 50000r = 3,000,000r / 84s = 35.7K r/s <-- remote
  // hati.publish(`SET test_key ${valueMsg}`),
  // hati.publish(`GET test_key`),
  // hati.publish(`SET key ${valueMsg}`),
  // hati.publish(`SET key ${valueMsg}`),
  // hati.publish(`SET key ${valueMsg}`),
  // hati.publish(`SET key ${valueMsg}`),
  // hati.publish(`SET key ${valueMsg}`),
  // hati.publish(`SET key ${valueMsg}`),
  // hati.publish(`SET key ${valueMsg}`),
  // hati.publish(`SET key ${valueMsg}`),
  // hati.publish(`SET key ${valueMsg}`),
  // hati.publish(`SET key ${valueMsg}`),
  // hati.publish(`SET key ${valueMsg}`),
  // hati.publish(`SET key ${valueMsg}`),
  // hati.publish(`SET key ${valueMsg}`),
  // hati.publish(`SET key ${valueMsg}`),
  // hati.publish(`SET key ${valueMsg}`),
  // hati.publish(`SET key ${valueMsg}`),
  // hati.publish(`SET key ${valueMsg}`),
  // hati.publish(`SET key ${valueMsg}`),
  // hati.publish(`SET key ${valueMsg}`),
  // hati.publish(`SET key ${valueMsg}`),
  // hati.publish(`SET key ${valueMsg}`),
  // hati.publish(`SET key ${valueMsg}`),
  // hati.publish(`SET key ${valueMsg}`),
  // hati.publish(`SET key ${valueMsg}`),
  // hati.publish(`SET key ${valueMsg}`),
  // hati.publish(`SET key ${valueMsg}`),
  // hati.publish(`SET key ${valueMsg}`),
  // hati.publish(`SET key ${valueMsg}`),
  // hati.publish(`SET key ${valueMsg}`),
  // hati.publish(`SET key ${valueMsg}`),
  // hati.publish(`SET key ${valueMsg}`),
  // hati.publish(`SET key ${valueMsg}`),
  // hati.publish(`SET key ${valueMsg}`),
  // hati.publish(`SET key ${valueMsg}`),
  // hati.publish(`SET key ${valueMsg}`),
  // hati.publish(`SET key ${valueMsg}`),
  // hati.publish(`SET key ${valueMsg}`),
  // hati.publish(`SET key ${valueMsg}`),
  // hati.publish(`SET key ${valueMsg}`),
  // hati.publish(`SET key ${valueMsg}`),
  // hati.publish(`SET key ${valueMsg}`),
  // hati.publish(`SET key ${valueMsg}`),
  // hati.publish(`SET key ${valueMsg}`),
  // hati.publish(`SET key ${valueMsg}`),
  // hati.publish(`SET key ${valueMsg}`),
  // hati.publish(`SET key ${valueMsg}`),
  // hati.publish(`SET key ${valueMsg}`),
  // hati.publish(`SET key ${valueMsg}`),
  // hati.publish(`SET key ${valueMsg}`),
  // hati.publish(`SET key ${valueMsg}`),
  // hati.publish(`SET key ${valueMsg}`),
  // hati.publish(`SET key ${valueMsg}`),
  // hati.publish(`SET key ${valueMsg}`),
  // hati.publish(`SET key ${valueMsg}`),
  // hati.publish(`SET key ${valueMsg}`),
  // hati.publish(`SET key ${valueMsg}`),
  // hati.publish(`SET key ${valueMsg}`),
  // hati.publish(`SET key ${valueMsg}`),
  // /// ^^ 120clients * 50000r = 6,000,000r / s =  r/s <-- local
  // /// ^^ 120clients * 50000r = 6,000,000r / 95s =  63.1Kr/s <-- remote

  // hati.publish(`SET test_key ${valueMsg}`),
  // hati.publish(`GET test_key`),
  // hati.publish(`SET key ${valueMsg}`),
  // hati.publish(`SET key ${valueMsg}`),
  // hati.publish(`SET key ${valueMsg}`),
  // hati.publish(`SET key ${valueMsg}`),
  // hati.publish(`SET key ${valueMsg}`),
  // hati.publish(`SET key ${valueMsg}`),
  // hati.publish(`SET key ${valueMsg}`),
  // hati.publish(`SET key ${valueMsg}`),
  // hati.publish(`SET key ${valueMsg}`),
  // hati.publish(`SET key ${valueMsg}`),
  // hati.publish(`SET key ${valueMsg}`),
  // hati.publish(`SET key ${valueMsg}`),
  // hati.publish(`SET key ${valueMsg}`),
  // hati.publish(`SET key ${valueMsg}`),
  // hati.publish(`SET key ${valueMsg}`),
  // hati.publish(`SET key ${valueMsg}`),
  // hati.publish(`SET key ${valueMsg}`),
  // hati.publish(`SET key ${valueMsg}`),
  // hati.publish(`SET key ${valueMsg}`),
  // hati.publish(`SET key ${valueMsg}`),
  // hati.publish(`SET key ${valueMsg}`),
  // hati.publish(`SET key ${valueMsg}`),
  // hati.publish(`SET key ${valueMsg}`),
  // hati.publish(`SET key ${valueMsg}`),
  // hati.publish(`SET key ${valueMsg}`),
  // hati.publish(`SET key ${valueMsg}`),
  // hati.publish(`SET key ${valueMsg}`),
  // hati.publish(`SET key ${valueMsg}`),
  // hati.publish(`SET key ${valueMsg}`),
  // hati.publish(`SET key ${valueMsg}`),
  // hati.publish(`SET key ${valueMsg}`),
  // hati.publish(`SET key ${valueMsg}`),
  // hati.publish(`SET key ${valueMsg}`),
  // hati.publish(`SET key ${valueMsg}`),
  // hati.publish(`SET key ${valueMsg}`),
  // hati.publish(`SET key ${valueMsg}`),
  // hati.publish(`SET key ${valueMsg}`),
  // hati.publish(`SET key ${valueMsg}`),
  // hati.publish(`SET key ${valueMsg}`),
  // hati.publish(`SET key ${valueMsg}`),
  // hati.publish(`SET key ${valueMsg}`),
  // hati.publish(`SET key ${valueMsg}`),
  // hati.publish(`SET key ${valueMsg}`),
  // hati.publish(`SET key ${valueMsg}`),
  // hati.publish(`SET key ${valueMsg}`),
  // hati.publish(`SET key ${valueMsg}`),
  // hati.publish(`SET key ${valueMsg}`),
  // hati.publish(`SET key ${valueMsg}`),
  // hati.publish(`SET key ${valueMsg}`),
  // hati.publish(`SET key ${valueMsg}`),
  // hati.publish(`SET key ${valueMsg}`),
  // hati.publish(`SET key ${valueMsg}`),
  // hati.publish(`SET key ${valueMsg}`),
  // hati.publish(`SET key ${valueMsg}`),
  // hati.publish(`SET key ${valueMsg}`),
  // hati.publish(`SET key ${valueMsg}`),
  // hati.publish(`SET key ${valueMsg}`),
  // hati.publish(`SET key ${valueMsg}`),
  // hati.publish(`SET test_key ${valueMsg}`),
  // hati.publish(`GET test_key`),
  // hati.publish(`SET key ${valueMsg}`),
  // hati.publish(`SET key ${valueMsg}`),
  // hati.publish(`SET key ${valueMsg}`),
  // hati.publish(`SET key ${valueMsg}`),
  // hati.publish(`SET key ${valueMsg}`),
  // hati.publish(`SET key ${valueMsg}`),
  // hati.publish(`SET key ${valueMsg}`),
  // hati.publish(`SET key ${valueMsg}`),
  // hati.publish(`SET key ${valueMsg}`),
  // hati.publish(`SET key ${valueMsg}`),
  // hati.publish(`SET key ${valueMsg}`),
  // hati.publish(`SET key ${valueMsg}`),
  // hati.publish(`SET key ${valueMsg}`),
  // hati.publish(`SET key ${valueMsg}`),
  // hati.publish(`SET key ${valueMsg}`),
  // hati.publish(`SET key ${valueMsg}`),
  // hati.publish(`SET key ${valueMsg}`),
  // hati.publish(`SET key ${valueMsg}`),
  // hati.publish(`SET key ${valueMsg}`),
  // hati.publish(`SET key ${valueMsg}`),
  // hati.publish(`SET key ${valueMsg}`),
  // hati.publish(`SET key ${valueMsg}`),
  // hati.publish(`SET key ${valueMsg}`),
  // hati.publish(`SET key ${valueMsg}`),
  // hati.publish(`SET key ${valueMsg}`),
  // hati.publish(`SET key ${valueMsg}`),
  // hati.publish(`SET key ${valueMsg}`),
  // hati.publish(`SET key ${valueMsg}`),
  // hati.publish(`SET key ${valueMsg}`),
  // hati.publish(`SET key ${valueMsg}`),
  // hati.publish(`SET key ${valueMsg}`),
  // hati.publish(`SET key ${valueMsg}`),
  // hati.publish(`SET key ${valueMsg}`),
  // hati.publish(`SET key ${valueMsg}`),
  // hati.publish(`SET key ${valueMsg}`),
  // hati.publish(`SET key ${valueMsg}`),
  // hati.publish(`SET key ${valueMsg}`),
  // hati.publish(`SET key ${valueMsg}`),
  // hati.publish(`SET key ${valueMsg}`),
  // hati.publish(`SET key ${valueMsg}`),
  // hati.publish(`SET key ${valueMsg}`),
  // hati.publish(`SET key ${valueMsg}`),
  // hati.publish(`SET key ${valueMsg}`),
  // hati.publish(`SET key ${valueMsg}`),
  // hati.publish(`SET key ${valueMsg}`),
  // hati.publish(`SET key ${valueMsg}`),
  // hati.publish(`SET key ${valueMsg}`),
  // hati.publish(`SET key ${valueMsg}`),
  // hati.publish(`SET key ${valueMsg}`),
  // hati.publish(`SET key ${valueMsg}`),
  // hati.publish(`SET key ${valueMsg}`),
  // hati.publish(`SET key ${valueMsg}`),
  // hati.publish(`SET key ${valueMsg}`),
  // hati.publish(`SET key ${valueMsg}`),
  // hati.publish(`SET key ${valueMsg}`),
  // hati.publish(`SET key ${valueMsg}`),
  // hati.publish(`SET key ${valueMsg}`),
  // hati.publish(`SET key ${valueMsg}`),
  /// ^^ 180clients * 50000r = 6,000,000r / s =  K r/s <-- remote
  // ]);

  await hati.publish(`GET memory test_key`);
})();
